//
// Created by huachengli on 2/19/25.
// read vts data generated by citcoms
// CALCULATE MELT FRACTION ACCORDING TO SOLID/LIQUID TEMPERATURE
// use parameters from post.inp
// [citcoms]
// [melt]
//



#include "citcoms_related.h"
int main(int argc,char * argv[])
{
    char inp_file[4096] = "post.inp";
    switch(argc)
    {
        case 1:
            break;
        case 2:
            strcpy(inp_file,argv[1]);
            break;
        default:
            fprintf(stdout,"error in command line\n");
    }

    CitcomsData * _cdata = init_citcoms_data(inp_file);
    for(int k=_cdata->step0;k<_cdata->step1;k+=_cdata->step_inc)
    {
        load_citcoms_step(_cdata,k);
        if(k==_cdata->step0) init_sol_liq_prof(_cdata);
        update_melting(_cdata);
        char data_prefix[4096];
        snprintf(data_prefix,4096,"%s.%04d",_cdata->VtsPrefix, k);
        write_citcoms_step(_cdata,k);
        clean_citcoms_data(_cdata);
        fprintf(stdout,"processing %s[%d]\n",_cdata->VtsPrefix, k);
    }

    close_citcoms_data(_cdata);
    return 0;
}
